Management_system/Management_system/urls.py
from django.contrib import admin
from django.urls import path, re_path
from website.views import depart, pretty, user, admin, account, task

urlpatterns = [
    re_path(r'^$', account.login),
    # path("admin/", admin.site.urls),
    # 部门管理
    path("depart/list/", depart.depart_list, name='depart_list'),
    path("depart/add/", depart.depart_add, name='depart_add'),
    ##
    # http://127.0.0.1:8000/depart/1/edit
    # http://127.0.0.1:8000/depart/1/delete
    ##
    path("depart/<int:nid>/delete/", depart.depart_delete, name='depart_delete'),
    path("depart/<int:nid>/edit/", depart.depart_edit, name='depart_edit'),

    # 用户管理
    path("user/list/", user.user_list, name="user_list"),
    path("user/add/", user.user_add, name='user_add'),
    path("user/<int:nid>/edit/", user.user_edit, name="user_edit"),
    path("user/<int:nid>/delete/", user.user_delete, name="user_delete"),

    # 靓号管理
    path("pretty/list/", pretty.pretty_list, name="pretty_list"),
    path("pretty/add/", pretty.pretty_add, name="pretty_add"),
    path("pretty/<int:nid>/edit/", pretty.pretty_edit, name="pretty_edit"),
    path("pretty/<int:nid>/delete/", pretty.pretty_delete, name="pretty_delete"),

    # 管理员管理
    path("admin/list/", admin.admin_list, name="admin_list"),
    path("admin/add/", admin.admin_add, name="admin_add"),
    path("admin/<int:nid>/edit", admin.admin_edit, name="admin_edit"),
    path("admin/<int:nid>/delete", admin.admin_delete, name="admin_delete"),
    path("admin/<int:nid>/reset", admin.admin_reset, name="admin_reset"),

    # 登录
    path("login/", account.login, name="login"),
    path("logout/", account.logout, name='logout'),
    path("image/code/", account.image_code, name="image_code"),

    # ajax页面
    path("task/list/", task.task_list, name="task_list"),
    path("task/ajax/", task.task_ajax, name="task_ajax")
]

Management_system/website/models.py
from django.db import models


# Create your models here.
class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name="标题", max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""

    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    """
    max_digits=10 总共的数字长度为10
    decimal_places=2 小数位为2
    """
    account = models.DecimalField(
        verbose_name="账户余额", max_digits=10, decimal_places=2, default=0
    )
    onboarding_time = models.DateField(verbose_name="入职时间")

    # 这样写无约束不可取
    # depart_id = models.BigAutoField(verbose_name="部门ID")

    """
    有约束
    -to, 与哪张表关联; -to_field与表中哪一列数据关联
    Django自动
     - 写的depart
     - 生成数据列 depart_id
    若关联的表中有数据被删除了，两种处理办法
    1. depart = models.ForeignKey(to="Department", to_field="id", on_delete=models.CASCADE) 当前表对应的内容也跟着删除
    2. depart = models.ForeignKey(
        to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL
    ) 当前表对应的内容置空
    """
    depart = models.ForeignKey(verbose_name="部门",
                               to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL
                               )

    """
    添加性别列：在DJango中用代码约束内容只有男或女
    """
    gender_choices = ((1, "男"), (2, "女"))
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class PrettyNum(models.Model):
    mobile = models.CharField(max_length=11, verbose_name="手机号")

    price = models.IntegerField(verbose_name="价格", default=0)

    level_choices = (
        (1, '1级'),
        (2, '2级'),
        (3, '3级'),
        (4, '4级'),
    )
    level = models.SmallIntegerField(choices=level_choices, verbose_name="级别", default=1)

    status_choices = (
        (1, "已占用"),
        (2, "未使用"),
    )
    status = models.SmallIntegerField(choices=status_choices, verbose_name="状态", default=2)


# 管理员
class Admin(models.Model):
    """管理员"""
    username = models.CharField(max_length=32, verbose_name="用户名")
    password = models.CharField(max_length=64, verbose_name="密码")

Management_system/website/views/account.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2024/3/21 15:48
# @Author  : Aries
# @File    : account.py
# @Description : 登录页面视图函数
from django.shortcuts import render, redirect, reverse, HttpResponse
from website import models
from website.utils.form import LoginForm
from website.utils.imgcheck import check_code
from io import BytesIO


def login(request):
    """登录"""
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(request.POST)

    if form.is_valid():
        # 验证成功
        # 去数据库校验用户名密码是否正确，如果错误，获取None

        # 验证码校验
        user_input_code = form.cleaned_data.pop('code')
        code_dict = request.session.get('image_code', "")
        if code_dict['code'].upper() != user_input_code.upper():
            form.add_error('code', '验证码错误')
            return render(request, 'login.html', {'form': form})

        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error('password', '用户名或密码错误')
            return render(request, 'login.html', {'form': form})

        # 用户名和密码正确
        # 网站生成随机字符串，写到浏览器的cookie，写到session中
        request.session['info'] = {'id': admin_object.id, 'name': admin_object.username}
        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect(reverse('admin_list'))
    return render(request, 'login.html', {'form': form})


def logout(request):
    """注销"""
    request.session.clear()
    return redirect(reverse('login'))


def image_code(request):
    """生成验证码图片"""
    # 调用pillow生成验证码
    img, code_str = check_code()
    # 将验证码文字写入session
    request.session['image_code'] = {'code': code_str}
    # 设置session 60秒超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

Management_system/website/views/admin.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2024/3/20 11:28
# @Author  : Aries
# @File    : admin.py
# @Description : admin视图函数

from django.shortcuts import render, redirect, reverse
from website import models
from website.utils.pagenation import Pagination
from website.utils.form import AdminModelForm, AdminResetModelForm


def admin_list(request):
    """管理员账户"""

    data_dict = {}
    search_data = request.GET.get('q', "")
    if search_data is not None:
        data_dict['username__contains'] = search_data

    queryset = models.Admin.objects.filter(**data_dict)
    page_object = Pagination(request=request, queryset=queryset, page_size=10)

    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html()
    }

    return render(request, 'admin_list.html', context)


def admin_add(request):
    """添加管理员"""
    title = "新建管理员"
    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'change.html', {'form': form, 'title': title})

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('admin_list'))

    return render(request, 'change.html', {'form': form, 'title': title})


def admin_edit(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()

    if not row_object:
        return redirect(reverse('admin_list'))

    title = '编辑管理员'

    if request.method == 'GET':
        form = AdminModelForm(instance=row_object)
        return render(request, 'change.html', {'form': form, 'title': title})

    form = AdminModelForm(instance=row_object, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('admin_list'))

    return render(request, 'change.html', {'form': form, 'title': title})


def admin_delete(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect(reverse('admin_list'))


def admin_reset(request, nid):
    """重置密码"""
    row_object = models.Admin.objects.filter(id=nid).first()

    if not row_object:
        return redirect(reverse('admin_list'))

    title = f"重置账户{row_object.username}的密码"

    if request.method == 'GET':
        form = AdminResetModelForm()
        return render(request, 'change.html', {'form': form, 'title': title})

    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect(reverse('admin_list'))

    return render(request, 'change.html', {'form': form, 'title': title})

Management_system/website/views/depart.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2024/3/19 23:22
# @Author  : Aries
# @File    : depart.py
# @Description : department视图函数

from django.shortcuts import render, redirect
from website import models
from website.utils.pagenation import Pagination


def depart_list(request):
    """部门列表"""

    # 去数据库获取部门列表
    queryset = models.Department.objects.all()

    page_object = Pagination(request=request, queryset=queryset, page_size=1)

    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html()
    }

    return render(request, "depart_list.html", context)


def depart_add(request):
    """添加部门"""
    if request.method == 'GET':
        return render(request, 'depart_add.html')

    # 获取用户post过来的数据
    title = request.POST['title']

    # 保存到数据库
    models.Department.objects.create(title=title)

    # 重定向回部门列表
    return redirect('/depart/list')


def depart_delete(request, nid):
    """删除部门"""
    # 获取ID
    # http://127.0.0.1:8000/depart/delete/?nid=1
    # nid = request.GET.get('nid')
    # 第二种方法
    # http://127.0.0.1:8000/depart/1/edit
    # http://127.0.0.1:8000/depart/1/delete
    ##
    # 删除
    models.Department.objects.filter(id=nid).delete()
    # 跳转回部门列表
    return redirect('/depart/list/')


def depart_edit(request, nid):
    """修改部门"""
    if request.method == 'GET':
        row_object = models.Department.objects.filter(id=nid).first()
        return render(request, "depart_edit.html", {"row_object": row_object})
    # 找到字段并更新 models.Department.objects.filter(id=nid).update(title=request.POST['title'], 其他=xxx)
    models.Department.objects.filter(id=nid).update(title=request.POST['title'])
    return redirect('/depart/list/')

Management_system/website/views/pretty.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2024/3/19 23:22
# @Author  : Aries
# @File    : pretty.py
# @Description : prettyNum视图函数

from django.shortcuts import render, redirect, reverse
from website import models
from website.utils.pagenation import Pagination
from website.utils.form import PrettyModelForm, PrettyEditModelForm


# 靓号管理
def pretty_list(request):
    """获取靓号列表"""

    data_dict = {}
    search_data = request.GET.get('q', "")
    if search_data is not None:
        data_dict['mobile__contains'] = search_data

    # 分页
    queryset = models.PrettyNum.objects.filter(**data_dict).order_by("-level")

    page_object = Pagination(request=request, queryset=queryset)

    page_string = page_object.html()

    context = {
        'queryset': page_object.page_queryset,
        'search_data': search_data,
        'page_string': page_string,
        'total_page_count': page_object.total_page_count
    }

    return render(request, 'pretty_list.html', context)


def pretty_add(request):
    """添加靓号"""
    if request.method == 'GET':
        form = PrettyModelForm()
        return render(request, 'pretty_add.html', {'form': form})

    form = PrettyModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('pretty_list'))

    return render(request, 'pretty_add.html', {'form': form})


def pretty_edit(request, nid):
    """编辑靓号"""
    row_object = models.PrettyNum.objects.filter(id=nid).first()

    if request.method == 'GET':
        form = PrettyEditModelForm(instance=row_object)
        return render(request, 'pretty_edit.html', {'form': form})

    form = PrettyEditModelForm(instance=row_object, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/pretty/list/')

    return render(request, 'pretty_edit.html', {'form': form})


def pretty_delete(request, nid):
    """删除靓号"""
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect('/pretty/list/')

Management_system/website/views/task.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2024/3/24 14:48
# @Author  : Aries
# @File    : task.py
# @Description : ajax页面
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json


def task_list(request):
    return render(request, 'task_list.html')


@csrf_exempt
def task_ajax(request):
    print(request.GET)
    print(request.POST)
    # python 自带的json解析
    data_dict = request.POST
    # json_str = json.dumps(data_dict)
    # django自带的json解析
    return JsonResponse(data_dict)

Management_system/website/views/user.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2024/3/19 23:22
# @Author  : Aries
# @File    : user.py
# @Description : userInfo视图函数

from django.shortcuts import render, redirect, reverse
from website import models
from website.utils.pagenation import Pagination
from website.utils.form import UserModelForm


# 用户管理
def user_list(request):
    """用户管理"""

    # 获取所有的用户列表
    queryset = models.UserInfo.objects.all()

    page_object = Pagination(request, queryset, page_size=2)

    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html()
    }
    # python方法获取数据
    # item.get_xxx_display()可以自动读取从数据库读取choices
    # item.depart_id获取到的是数字，使用item.depart直接获取数字对应的对象
    # for item in queryset:
    # print(item.id, item.name, item.account, item.onboarding_time.strftime("%Y-%m-%d"), item.get_gender_display())
    # print(item.name, item.depart.title)

    return render(request, 'user_list.html', context)


def user_add(request):
    """添加用户"""
    if request.method == 'GET':
        form = UserModelForm()
        return render(request, "user_add.html", {"form": form})

    # 数据校验
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')

    return render(request, "user_add.html", {"form": form})


def user_edit(request, nid):
    row_object = models.UserInfo.objects.filter(id=nid).first()

    if request.method == 'GET':
        # 根据ID去数据库获取要编辑的那一行数据（对象），form = UserModelForm(instance=row_object)
        form = UserModelForm(instance=row_object)
        return render(request, 'user_edit.html', {'form': form})

    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 默认保存的是用户输入的数据
        # 若想保存用户输入以外的值，只需 form.instance.字段名 = 值
        form.save()
        return redirect(reverse('user_list'))

    return render(request, "user_edit.html", {"form": form})


def user_delete(request, nid):
    """删除用户"""
    obj = models.UserInfo.objects.filter(id=nid).delete()
    return redirect('/user/list')

Management_system/website/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">

            <a href="{% url 'admin_add' %}" class="btn btn-success" aria-hidden="true">
                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                新建管理员
            </a>

            <div style="float: right; width: 300px">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="查找管理员用户"
                               value="{{ search_data }}">
                        <span class="input-group-btn"><button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button></span>

                    </div>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-align-left"></span>
                管理员列表
            </div>

            <!-- Table -->
            <table class="table table-bodered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>重置密码</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <td>{{ item.username}}</td>
                        <td>*********</td>
                        <td>
                            <a href="{% url 'admin_reset' item.id %}">重置密码</a>
                        </td>
                        <td>
                            <a href="{% url 'admin_edit' item.id %}" class="btn btn-primary btn-xs">编辑</a>
                            <a href="{% url 'admin_delete' item.id %}" class="btn btn-danger btn-xs">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $("[type='number']").on("input", function (e) {
                    if (this.value > {{ total_page_count }})
                        this.value = {{ total_page_count }};
                    if (this.value < 1)
                        this.value = 1;
                }
            )
        })
    </script>
{% endblock %}

Management_system/website/templates/change.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ title }}</h3>
                </div>
                <div class="panel-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.label }}：{{ field }}
                                <span style="color: red">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Management_system/website/templates/depart_add.html
{% extends 'layout.html' %}
{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">新建部门</h3>
                </div>
                <div class="panel-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>标题</label>
                            <input type="text" class="form-control" placeholder="标题" name="title">
                        </div>

                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Management_system/website/templates/depart_edit.html
{% extends 'layout.html' %}
{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">修改部门</h3>
                </div>
                <div class="panel-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>标题</label>
                            <input type="text" class="form-control" placeholder="标题" name="title"
                                   value="{{ row_object.title }}">
                        </div>

                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Management_system/website/templates/depart_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <div><a href="/depart/add/" class="btn btn-success">
                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                新建部门
            </a></div>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-align-left"></span>
                部门列表
            </div>

            <!-- Table -->
            <table class="table table-bodered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>名称</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.title }}</td>
                        <td>
                            <a href="/depart/{{ obj.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                            <a href="/depart/{{ obj.id }}/delete/" class="btn btn-danger btn-xs">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}

Management_system/website/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %} <link rel="stylesheet" href="{% static "plugins/css/bootstrap.min.css" %}"> {% endcomment %}
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    {% block css %}{% endblock %}
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
    <script src="{% static "js/jquery.js" %}"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">用户管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'admin_list' %}">管理员账户</a></li>
                <li><a href="{% url 'depart_list' %}">部门管理</a></li>
                <li><a href="{% url 'user_list' %}">用户管理</a></li>
                <li><a href="{% url 'pretty_list' %}">靓号管理</a></li>
                <li><a href="{% url 'task_list' %}">任务管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.session.info.name }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'logout' %}">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.container-fluid -->
</nav>
<div>
    {% block content %}{% endblock %}
</div>
{% comment %} <script src="{% static "plugins/js/bootstrap.min.js" %}"></script> {% endcomment %}
<script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
{% block js %}{% endblock %}
</body>
</html> 

Management_system/website/templates/pretty_add.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">新建靓号</h3>
                </div>
                <div class="panel-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.label }}：{{ field }}
                                <span style="color: red">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Management_system/website/templates/pretty_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">编辑靓号</h3>
                </div>
                <div class="panel-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.label }}：{{ field }}
                                <span style="color: red">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Management_system/website/templates/pretty_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">

            <a href="{% url 'pretty_add' %}" class="btn btn-success" aria-hidden="true">
                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                新建靓号
            </a>

            <div style="float: right; width: 300px">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="查找靓号"
                               value="{{ search_data }}">
                        <span class="input-group-btn"><button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button></span>

                    </div>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-align-left"></span>
                靓号列表
            </div>

            <!-- Table -->
            <table class="table table-bodered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>号码</th>
                    <th>价格</th>
                    <th>级别</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <td>{{ item.mobile }}</td>
                        <td>{{ item.price }}</td>
                        <td>{{ item.get_level_display }}</td>
                        <td>{{ item.get_status_display }}</td>
                        <td>
                            <a href="{% url 'pretty_edit' item.id %}" class="btn btn-primary btn-xs">编辑</a>
                            <a href="{% url 'pretty_delete' item.id %}" class="btn btn-danger btn-xs">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
    <script>
    $(document).ready(function() {
        $("[type='number']").on("input", function (e) {
                if (this.value > {{ total_page_count }})
                    this.value = {{ total_page_count }};
                if (this.value < 1)
                    this.value = 1;
            }
        )
    })
    </script>
{% endblock %}

Management_system/website/templates/user_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.min.css' %}">
    <link href="https://www.itxst.com/package/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.min.css"
          rel="stylesheet">
{% endblock %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">新建用户</h3>
                </div>
                <div class="panel-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.label }}：{{ field }}
                                <span style="color: red">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="https://www.itxst.com/package/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://www.itxst.com/package/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script>
    $(document).ready(function(e) {
        $("#id_onboarding_time").datepicker({
            language: 'zh-CN', //设置语言
            autoclose: true, //选择后自动关闭
            clearBtn: true,//清除按钮
            format: "yyyy-mm-dd"//日期格式
        });
    })
    </script>
{% endblock %}